#!/bin/sh
# modified version of dmenu_run to run programs with urxvtcd and shell

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi
IFS=:
if stest -dqr -n "$cache" $PATH; then
  L=$(stest -flx $PATH | sort -u | tee "$cache" | ~/bin/my-rofi "$@")
else
  L=$(~/bin/my-rofi "$@" < "$cache")
fi
urxvtcd -e zsh -c "$L"
