#!/bin/bash

# $1 is server
# $2 is user
# $3 is source dir
# $4 is target dir

SERVER=$1
USER=$2
LOCAL=$3
REMOTE=$4
if test "$#" -ne 4; then
    echo "Illegal number of parameters"
    exit 42
fi
lftp -c "open ftp://$USER@$SERVER;
lcd $LOCAL;
cd $REMOTE
mirror --reverse --verbose"

