#!/bin/bash

ROFI=$(pidof $(which rofi))
if [ ! -z "$ROFI" ]
then
  kill "$ROFI"
fi
if command -v rofi >/dev/null 2>&1
then
  # lazy-grab makes it show on keydown
  exec rofi -lazy-grab -terminal ~/bin/urxvtcdfont "$@"
else
  exec dmenu
fi

