#!/bin/bash

# https://bugzilla.samba.org/show_bug.cgi?id=10356
# support/rsync-no-vanished

# also disable controlmaster to silence warnings


IGNOREEXIT=24
IGNOREOUT='^(file has vanished: |rsync warning: some files vanished before they could be transferred|rsync: read errors mapping.*: No data available)'

set -o pipefail

rsync -e "ssh -o ControlPath=/nowhere -o ControlMaster=no" "${@}" 2>&1 | (egrep -v "$IGNOREOUT" || true)
ret=$?

if [[ $ret == $IGNOREEXIT ]]; then
    ret=0
fi

exit $ret

